# Generated by Django 4.0.4 on 2022-05-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydesksethubusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
